#!/bin/sh
# Renders CLIProxyAPI's config.yaml from Railway environment variables and
# starts the proxy. The config is regenerated on every boot (env is the
# source of truth); Codex OAuth credentials persist across deploys on the
# Railway volume mounted at /data.
set -eu

: "${AI_GATEWAY_API_KEY:?AI_GATEWAY_API_KEY must be set (the key the backend uses to call this proxy)}"
: "${CLIPROXY_MANAGEMENT_KEY:?CLIPROXY_MANAGEMENT_KEY must be set (password for the management panel)}"

AUTH_DIR="${CLIPROXY_AUTH_DIR:-/data/auths}"
LISTEN_PORT="${PORT:-8317}"

mkdir -p "$AUTH_DIR"

cat > /CLIProxyAPI/config.yaml <<EOF
# Generated by entrypoint.sh on container start. Do not edit here; change
# the Railway service variables instead.
host: ""
port: ${LISTEN_PORT}

auth-dir: "${AUTH_DIR}"

api-keys:
  - "${AI_GATEWAY_API_KEY}"

# The management panel is how the Codex OAuth login is completed on this
# headless service. It is protected by the secret key; requests without it
# are rejected.
remote-management:
  allow-remote: true
  secret-key: "${CLIPROXY_MANAGEMENT_KEY}"

request-retry: 3
logging-to-file: false
EOF

# config.yaml sits at the binary's default lookup path (its working
# directory), so no config flag is needed.
cd /CLIProxyAPI
exec ./CLIProxyAPI
