#!/bin/sh
# Renders CLIProxyAPI's config.yaml from Railway environment variables and
# starts the proxy. The config is regenerated on every boot (env is the
# source of truth); Codex OAuth credentials persist across deploys on the
# Railway volume mounted at /data.
#
# OPS-07: operator values are escaped as YAML double-quoted scalars. A raw
# quote or backslash previously broke the generated YAML; values containing
# a newline/CR are refused without printing the value.
set -eu

: "${AI_GATEWAY_API_KEY:?AI_GATEWAY_API_KEY must be set (the key the backend uses to call this proxy)}"
: "${CLIPROXY_MANAGEMENT_KEY:?CLIPROXY_MANAGEMENT_KEY must be set (password for the management panel)}"

AUTH_DIR="${CLIPROXY_AUTH_DIR:-/data/auths}"
LISTEN_PORT="${PORT:-8317}"
CONFIG_PATH="${CLIPROXY_CONFIG_PATH:-/CLIProxyAPI/config.yaml}"

# POSIX sh only: no bash [[, arrays, or ${var//...} expansions.

yaml_escape() {
  _ye_value="$1"
  _ye_nl='
'
  _ye_cr=$(printf '\r')
  case "$_ye_value" in
    *"$_ye_nl"*|*"$_ye_cr"*)
      printf '%s\n' "entrypoint.sh: refusing to write config: value contains an unsupported newline (value not printed)" >&2
      return 1
      ;;
  esac
  # Escape backslash first, then double quotes, for YAML double-quoted style.
  # Other characters (including :, #, spaces) are literal inside quotes.
  printf '%s' "$_ye_value" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

case "$LISTEN_PORT" in
  ''|*[!0-9]*)
    printf '%s\n' "entrypoint.sh: refusing to write config: PORT must be an integer 1-65535" >&2
    exit 1
    ;;
esac
if [ "$LISTEN_PORT" -lt 1 ] || [ "$LISTEN_PORT" -gt 65535 ]; then
  printf '%s\n' "entrypoint.sh: refusing to write config: PORT must be an integer 1-65535" >&2
  exit 1
fi

ESCAPED_AUTH_DIR="$(yaml_escape "$AUTH_DIR")"
ESCAPED_API_KEY="$(yaml_escape "$AI_GATEWAY_API_KEY")"
ESCAPED_MGMT_KEY="$(yaml_escape "$CLIPROXY_MANAGEMENT_KEY")"

mkdir -p "$AUTH_DIR"
CONFIG_DIR=$(dirname "$CONFIG_PATH")
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_PATH" <<EOF
# Generated by entrypoint.sh on container start. Do not edit here; change
# the Railway service variables instead.
host: ""
port: ${LISTEN_PORT}

auth-dir: "${ESCAPED_AUTH_DIR}"

api-keys:
  - "${ESCAPED_API_KEY}"

# The management panel is how the Codex OAuth login is completed on this
# headless service. It is protected by the secret key; requests without it
# are rejected.
remote-management:
  allow-remote: true
  secret-key: "${ESCAPED_MGMT_KEY}"

request-retry: 3
logging-to-file: false
EOF

if [ "${CLIPROXY_SKIP_EXEC:-0}" = "1" ]; then
  exit 0
fi

# config.yaml sits at the binary's default lookup path (its working
# directory), so no config flag is needed.
cd /CLIProxyAPI
exec ./CLIProxyAPI
